apiVersion: v1
kind: Namespace
metadata:
  name: ywc-api

---
# ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: ywc-api-config
  namespace: ywc-api
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "ywc"
  DB_USER: "ywc"
  CORS_ORIGIN: "*"
  LOG_LEVEL: "info"

---
# Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: ywc-api-secrets
  namespace: ywc-api
type: Opaque
data:
  DB_PASSWORD: eW91cndlYWx0aGNvYWNo  # base64 encoded "yourwealthcoach"
  JWT_SECRET: c3VwZXItc2VjcmV0LWp3dC1rZXk=  # base64 encoded "super-secret-jwt-key"

---
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ywc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "ywc"
        - name: POSTGRES_USER
          value: "ywc"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ywc-api-secrets
              key: DB_PASSWORD
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - ywc
              - -d
              - ywc
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - ywc
              - -d
              - ywc
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ywc-api
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP

---
# PostgreSQL PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: ywc-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# YWC API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ywc-api
  namespace: ywc-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ywc-api
  template:
    metadata:
      labels:
        app: ywc-api
    spec:
      initContainers:
      - name: db-migration
        image: ywc-api:latest
        command: ["node", "deploy/db-setup.js"]
        envFrom:
        - configMapRef:
            name: ywc-api-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ywc-api-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ywc-api-secrets
              key: JWT_SECRET
      containers:
      - name: ywc-api
        image: ywc-api:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: ywc-api-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ywc-api-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ywc-api-secrets
              key: JWT_SECRET
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
# YWC API Service
apiVersion: v1
kind: Service
metadata:
  name: ywc-api-service
  namespace: ywc-api
spec:
  selector:
    app: ywc-api
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ywc-api-hpa
  namespace: ywc-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ywc-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 